### PR TITLE
Add CLI (fixes #14)

### LINKED ISSUE #14: Make CLI for convenient searches
The API should take inputs like `pipsearch pygame` and output the results in an easily readable format.

### PR DESCRIPTION
**Pull request by jarhill0**
This PR creates a command which is used by calling `$ pipsearch [search terms]` (ex. `$ pipsearch praw`, `$ pipsearch reddit api`) on the command line. It returns the first 5 results for the search term (less if there are fewer results).

### CODE REVIEW

**Comment by shubhodeep9** [comment]
@jarhill0 I love your approach, and first to have a crack at it. Cheers.
I have one enhancement in mind,
Add the limit part as an argument too.
So by default it gives 5, and if `--limit n` is given then it outputs _n_ results.

**Comment by jarhill0** [comment]
I'll work on this.

**Comment by shubhodeep9** [comment]
@jarhill0 Great!!

**Comment by jarhill0** [comment]
@shubhodeep9 Done.

**Comment by shubhodeep9** [comment]
@jarhill0 looks good to me.
I will merge it, go ahead and star the repo.

**Comment by jarhill0** [comment]
Done.

**Pull request merged**
