### PR TITLE
Fix AttributeError in search function

### PR DESCRIPTION
**Pull request by schedutron**

### CODE REVIEW

**Comment by schedutron** [comment]
Fixes #7.

**Comment by shubhodeep9** [comment]
@schedutron kindly rebase your branch and push again. So that I can rebase.

**Comment by schedutron** [comment]
@shubhodeep9 You mean fork?

**Comment by shubhodeep9** [comment]
@schedutron yes, the fork's feature branch, via which PR was created.
You may be able to see it shows conflicts.
So simple just fetch the upstream.

**Comment by schedutron** [comment]
@shubhodeep9 I've linted code further (#10), so now it has a pylint score of 8.89/10.

**Pull request merged**
