### PR TITLE
Added a new `setup.py` file. Fixes #2.

### LINKED ISSUE #2: Make setup.py
Make installer script for the library, and with requirements.

### PR DESCRIPTION
**Pull request by omaciel**
Added a new `setup.py` file to handle issue #2.

New `setup.py` file is a complete solution, specially if you're planning to add
tests to your project. I have also moved the `version` attribute to its own
file.

Some assumptions were made, such as that you want to support `Python 3` but
these can be easily changed if you don't want this. Comments on the file itself
should be helpful.

### CODE REVIEW

**Comment by omaciel** [comment]
```shell
pip install -e .
Obtaining file:///Users/omaciel/hacking/pipsearch
Collecting beautifulsoup4 (from pipsearch==0.0.1)
  Downloading beautifulsoup4-4.6.0-py3-none-any.whl (86kB)
    100% |████████████████████████████████| 92kB 993kB/s
Collecting requests (from pipsearch==0.0.1)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->pipsearch==0.0.1)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->pipsearch==0.0.1)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->pipsearch==0.0.1)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->pipsearch==0.0.1)
  Using cached idna-2.6-py2.py3-none-any.whl
Installing collected packages: beautifulsoup4, certifi, chardet, urllib3, idna, requests, pipsearch
  Running setup.py develop for pipsearch
Successfully installed beautifulsoup4-4.6.0 certifi-2017.7.27.1 chardet-3.0.4 idna-2.6 pipsearch requests-2.18.4 urllib3-1.22
(pipsearch) hacking/pipsearch [master●] » python
Python 3.6.1 (default, Mar 23 2017, 16:49:06)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pipsearch
>>> pipsearch.search('requests')
[{'name': 'awsrequests 0.0.12', 'link': 'https://pypi.python.org/pypi/awsrequests/0.0.12', 'weight': 9, 'description': 'For making signed requests to AWS API Gateway endpoints'}, {'name': 'cache_requests 4.0.0', 'link': 'https://pypi.python.org/pypi/cache_requests/4.0.0', 'weight': 9, 'description': 'Simple. Powerful. Persistent LRU caching for the requests library.'},....
```

**Comment by omaciel** [comment]
@shubhodeep9 give it a shot?

**Comment by shubhodeep9** [comment]
@omaciel let me try this out, and get back to you

**Comment by omaciel** [comment]
@shubhodeep9 got an update on this by any chance? I saw that you merged other PRs, so I had to fix a conflict already to make sure that this can be merged smoothly.

**Comment by shubhodeep9** [comment]
@omaciel sorry for the delay, its hard to track so many repositories' issues.
I will merge the PR right away.
GO ahead and star the repo.
Happy Hacking!

**Comment by omaciel** [comment]
@shubhodeep9 no worries and thank you!

**Pull request merged**
