### PR TITLE
 Fixed issue where package threw AttributeException when no result was found

### PR DESCRIPTION
**Pull request by parth-verma**
Resolves issue #9

### CODE REVIEW

**Review by shubhodeep9 — CHANGES_REQUESTED** [review]
Your code is oddly indented, kindly use tabs=space4 indentation.

**Comment by parth-verma** [comment]
Must have been done by the ide😐. 
So you want it to be indented with tabs of width equal to 4 spaces if i am interpreting this correctly?

**Comment by parth-verma** [comment]
Changed indents to space. Kindly check.
Also to avoid regarding such stuff in the future i would suggesting adding a Contribution.md to the repo with all such details.😀

**Review by shubhodeep9 — APPROVED** [review]

**Comment by shubhodeep9** [comment]
@party98 Yes this satisfies.
Yes I should do that 😪  too lazy

**Pull request merged**
